config/routes.rb
Rails.application.routes.draw do
  get 'product/new'
  root 'welcome#new'
  get    'signup'   => 'signup#new'
  post   'signup'   => 'signup#create'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout' => 'sessions#logout'
  delete 'logout' => 'sessions#logout'
  get    'category'   => 'category#new'
  post    'category'   => 'category#create'
  get    'category/index'   => 'category#index'
  get    'product/:id' => 'product#show', as: 'product_show'
  get    'product/:id/new'   => 'product#new', as: 'product_renew'
  post   'product/:id/new'   => 'product#create'
  delete  'product/delete' => 'product#delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categorys = Category.all
  end

  def new
  end
  
  def create
    @category = Category.new(cname: params[:category][:cname])
    if @category.save
      # flash[:success] = "Welcome our website!"
      redirect_to category_index_path
    else
      render 'new'
    end
  end

  private

    def category_params
      params.require(:product).permit(:pname, :image, :price)
    end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  require 'carrierwave/orm/activerecord'
  def show
    @category = Category.find(params[:id])
    @product = Product.select('*').where('category_id = ?', @category.id)
    Rails.logger.info("What product")
    Rails.logger.info(@product.name)
  end

  def new
    @category = Category.find(params[:id])
    Rails.logger.info("What id")
    Rails.logger.info(@category)
  end
  
  def create
    @category = Category.find(params[:id])
    @product = Product.new(category_params)
    @product.category_id = @category.id
    Rails.logger.info("Category")
    Rails.logger.info(@product)
    if @product.save
      # flash[:success] = "Welcome our website!"
      redirect_to product_show_path
    else
      render 'new'
    end
  end

  def delete
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to product_path

  end

  private

    def category_params
      params.require(:product).permit(:pname, :image, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to category_index_path
    else
      # Create an error message.
      flash[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def logout
    log_out
    redirect_to root_path
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      # flash[:success] = "Welcome our website!"
      redirect_to login_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def log_out
        session[:user_id] = nil
        @current_user = nil
    end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/category/index.html.erb
<div class="row">
    <%= render "/shared/loginnav" %>
</div>
<div style="overflow-x: hidden">
  <div calss ="row">
      <div class="col-sm-10 centered">
        <table  class="table table-striped">                
          <thead>
            <tr>
              <th>Category Name</th>
            </tr>
          </thead>         
          <% @categorys.each do |data| %>       
          <tr>
            <td><label><b><%= data.cname %></b></label></td>
            <td><%= link_to "add product", product_renew_path(data)%></td>
            <td><%= link_to "show product", product_show_path(data)%></td>
            <td><%= link_to "edit" %></td>
            <td><%= link_to "delete"%></td>
          </tr>
          <% end %>                        
        </table>  
      </div>
  </div>
</div>
<style>
.centered {
  position: absolute;
  position: fixed;
  top: 15%;
  left: 5%;
}
</style>

app/views/category/new.html.erb
<div class="row">
    <%= render "/shared/loginnav" %>
</div>
<div calss ="row">
    <%= image_tag("shopping2.jpg", size: "1370x520") %>
    <div class="col-md-6 float-end centered">
      <button id="MybtnModal" class="btn btn-outline-success float-end mt-3 me-4" type="submit">Add New Category</button>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groceryapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: #ddd6d4;">
    <%= yield %>
  </body>
</html>

app/views/product/new.html.erb
<div class="row">
    <%= render "/shared/nav" %>
</div>
<div  class="row">
  <%= image_tag("shopping2.jpg", size: "1370x520") %>
  <div class="col-sm-10 centered">
    <div class="card mx-auto mt-5" style="width: 23rem; background: #8ab3f9;">
      <h4 class="card-title mx-auto mt-3">Add New Product</h4>
      <div class="card-body">
        <div class="row">
          <div class="col-md-12 col-md-offset-3">
            <%= form_for(:product, url: product_renew_path) do |f| %>
            <%= render 'shared/error_messages' %>
            <div class="row mt-3">
                <div class="col-md-4">
                  <%= f.label :CategoryName %>
                </div>
                <div class="col-md-8">
                  <%= @category.cname %>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col-md-4">
                  <%= f.label :ProductName %>
                </div>
                <div class="col-md-8">
                  <%= f.text_field :pname, class: 'form-control' %>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col-md-4">
                  <%= f.label :Image %>
                </div>
                <div class="col-md-8">
                  <%= f.file_field :image, class: 'form-control' %>
                </div>
              </div>
              <div class="row mt-3">
                <div class="col-md-4">
                  <%= f.label :Price %>
                </div>
                <div class="col-md-8">
                  <%= f.text_field :price, class: 'form-control' %>
                </div>
              </div>
                <%= f.submit "Register", class: "btn btn-primary ms-5 mt-3"%>
                <%= f.submit "Cancel", class: "btn btn-primary ms-4 mt-3"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
.centered {
  position: absolute;
  position: fixed;
  top: 15%;
  left: 12%;
}
</style>

app/views/product/show.html.erb
<div class="row">
    <%= render "/shared/loginnav" %>
</div>
<div style="overflow-x: hidden">
  <div calss ="row">
      <div class="col-sm-10 centered">
        <table  class="table table-striped">                
          <thead>
            <tr>
              <th>Category Name</th>
            </tr>
          </thead>  
          <% @product.each do |data| %>       
          <tr>
            <td><label><b><%= data.pname %></b></label></td>
            <td><label><b><%= data.image %></b></label></td>
            <td><%= link_to "edit" %></td>
            <td><%= link_to 'Destroy', product_delete_path(data), method: :delete, data: { confirm: 'Are You sure?' } %></td>
            <td><%= link_to "delete", product_delete_path(data)%></td>
          </tr>
          <% end %>                      
        </table>  
      </div>
  </div>
</div>
<style>
.centered {
  position: absolute;
  position: fixed;
  top: 15%;
  left: 5%;
}
</style>

app/views/shared/_error_messages.html.erb
<% flash.each do |name, message| %>
  <% if name == 'danger' %>
    <div class="alert alert-<%= name %>">
    <% if Array === message %>
      <ul>
        <% message.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% else %>
      <%= message %>
    <% end %>
    </div>
  <% elsif name == 'success' %>
    <div class="alert alert-<%= name %>">
      <%= message %>
    </div>
  <% else %>
    <div class="alert alert-<%= name %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_loginnav.html.erb
<nav class="navbar navbar-expand-lg navbar-light"  style="background: #d0c5c2;">
  <div class="container-fluid">
  <p class="fst-italic fw-bold fs-2 ps-2">GLOCERY</p>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto ms-3 mb-2 mb-lg-0">
        <li class="nav-item fs-4">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item fs-4">
          <a class="nav-link" id="MybtnModal" href="#">Category</a>
        </li>
        <li class="nav-item fs-4">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div class="modal fade" id="Mymodal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Add New Category</h4>                                                             
			</div> 
			<div class="modal-body">
				<%= form_for(:category, url: category_path) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="row mt-3">
            <div class="col-md-4">
              <%= f.label :CategoryName %>
            </div>
            <div class="col-md-8">
              <%= f.text_field :cname, class: 'form-control' %>
            </div>
          </div>
          <%= f.submit "Register", class: "btn btn-primary ms-5 mt-3"%>
          <%= f.submit "Cancel", class: "btn btn-primary ms-4 mt-3"%>
        <% end %>
			</div>   
		</div>                                                                       
	</div>                                          
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$(document).ready(function(){
	$('#MybtnModal').click(function(){
  		$('#Mymodal').modal('show')
	});
});
</script>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light"  style="background: #d0c5c2;">
  <div class="container-fluid">
  <p class="fst-italic fw-bold fs-2 ps-2">GLOCERY</p>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto ms-3 mb-2 mb-lg-0">
        <li class="nav-item fs-4">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item fs-4">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item fs-4">
          <a class="nav-link" href="/signup">SignUp</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/signup/new.html.erb
<div class="row">
    <%= render "/shared/nav" %>
</div>
<div  class="row">
  <div class="card mx-auto mt-5" style="width: 23rem; background: #8ab3f9;">
    <h4 class="card-title mx-auto mt-3">SignUp</h4>
    <div class="card-body">
      <div class="row">
        <div class="col-md-12 col-md-offset-3">
          <%= form_for(:user, url: signup_path) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="row mt-3">
              <div class="col-md-4">
                <%= f.label :name %>
              </div>
              <div class="col-md-8">
                <%= f.text_field :name, class: 'form-control' %>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-md-4">
                <%= f.label :email %>
              </div>
              <div class="col-md-8">
                <%= f.email_field :email, class: 'form-control' %>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-md-4">
                <%= f.label :password %>
              </div>
              <div class="col-md-8">
                <%= f.password_field :password, class: 'form-control' %>
              </div>
            </div>
            <div class="row mt-3">
              <div class="col-md-4">
                <%= f.label :password_confirmation %>
              </div>
              <div class="col-md-8">
                <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
            </div>
            <%= f.submit "Sign up", class: "btn btn-primary ms-5 mt-3"%>
            <%= f.submit "Cancel", class: "btn btn-primary ms-4 mt-3"%>
          <% end %>
          <div class="row mt-2">
            <p>Already account? <%= link_to "Login!", login_path%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/new.html.erb
<div class="row">
    <%= render "/shared/nav" %>
</div>
<div class="row">
    <%= image_tag("home.jpg", size: "520x520") %>
    <div class="centered">
        <pre class="fst-italic fw-bold fs-5">Whatever you need,you can buy here everything.
You can buy easily at home.You have already account.
Please <%= link_to "Login!", login_path%>
        </pre>
    </div>
</div>
<style>
.centered {
  position: absolute;
  position: fixed;
  top: 25%;
  left: 30%;
}
</style>